all: memcost1 memcost2

memcost1: memcost1.cpp
	g++ -std=c++11 -Wall memcost1.cpp -o memcost1.out -O2
	
memcost2: memcost2.cpp
	g++ -std=c++11 -Wall memcost2.cpp -o memcost2.out -O2
	
clean:
	rm  *.out
